# Generated by Django 3.1.3 on 2020-11-24 04:15

import challenges.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('task', models.TextField(max_length=2000)),
                ('criteria', models.TextField(max_length=2000)),
                ('gender', models.CharField(choices=[('A', 'Any'), ('M', 'Male'), ('F', 'Female')], default='A', max_length=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('challenge_image', models.ImageField(null=True, upload_to=challenges.models.upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='Joined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_to_set', to='challenges.challenge')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_from_set', to='users.profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_challenge', to='challenges.challenge')),
                ('inv_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_from', to=settings.AUTH_USER_MODEL)),
                ('inv_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinishChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('video', models.FileField(upload_to=challenges.models.upload_video)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
